-- Audit retention is integrated after schema 11. No PRAGMA is set here.
-- A receipt remains pending/acknowledged; this separate fact is recorded only
-- after a matching authenticated Agent reports completed local confirmation.
CREATE TABLE config_restore_completions (
 receipt_id TEXT PRIMARY KEY REFERENCES config_restores(id),
 confirmed_at_ms INTEGER NOT NULL CHECK(confirmed_at_ms>0)
);
CREATE TABLE config_operation_targets (
 operation_id TEXT PRIMARY KEY REFERENCES config_operations(operation_id),
 changes_json TEXT NOT NULL CHECK(length(changes_json)<=65536 AND json_valid(changes_json) AND json_type(changes_json)='array')
);
INSERT INTO config_operation_targets SELECT o.operation_id,COALESCE((SELECT changes_json FROM config_operation_events e WHERE e.operation_id=o.operation_id AND changes_json<>'[]' ORDER BY event_id LIMIT 1),'[]') FROM config_operations o;
CREATE TABLE config_audit_retention (
 singleton INTEGER PRIMARY KEY CHECK(singleton=1),
 audit_rows INTEGER NOT NULL CHECK(audit_rows>=0),
 audit_bytes INTEGER NOT NULL CHECK(audit_bytes>=0),
 event_rows INTEGER NOT NULL CHECK(event_rows>=0),
 event_bytes INTEGER NOT NULL CHECK(event_bytes>=0),
 generation INTEGER NOT NULL DEFAULT 0 CHECK(generation>=0),
 pruned_rows INTEGER NOT NULL DEFAULT 0 CHECK(pruned_rows>=0),
 pruned_events INTEGER NOT NULL DEFAULT 0 CHECK(pruned_events>=0),
 last_gc_at_ms INTEGER NOT NULL DEFAULT 0 CHECK(last_gc_at_ms>=0)
);
INSERT INTO config_audit_retention(singleton,audit_rows,audit_bytes,event_rows,event_bytes) SELECT 1,(SELECT count(*) FROM config_audit_entries),(SELECT COALESCE(sum(96+length(CAST(COALESCE(kind,'') AS BLOB))+length(CAST(COALESCE(actor_kind,'') AS BLOB))+length(CAST(COALESCE(actor,'') AS BLOB))+length(CAST(COALESCE(observer,'') AS BLOB))+length(CAST(COALESCE(service_id,'') AS BLOB))+length(CAST(COALESCE(operation_id,'') AS BLOB))+length(CAST(COALESCE(state,'') AS BLOB))+length(CAST(COALESCE(code,'') AS BLOB))+length(CAST(COALESCE(summary_json,'') AS BLOB))+length(CAST(COALESCE(changes_json,'') AS BLOB))+length(CAST(COALESCE(origin_kind,'') AS BLOB))+length(CAST(COALESCE(origin_id,'') AS BLOB))),0) FROM config_audit_entries)+(SELECT COALESCE(sum(24+length(CAST(COALESCE(kind,'') AS BLOB))+length(CAST(COALESCE(name,'') AS BLOB))+length(CAST(COALESCE(action,'') AS BLOB))),0) FROM config_audit_objects),(SELECT count(*) FROM config_operation_events),(SELECT COALESCE(sum(64+length(CAST(COALESCE(operation_id,'') AS BLOB))+length(CAST(COALESCE(state,'') AS BLOB))+length(CAST(COALESCE(code,'') AS BLOB))+length(CAST(COALESCE(changes_json,'') AS BLOB))+length(CAST(COALESCE(actor,'') AS BLOB))),0) FROM config_operation_events);
CREATE TRIGGER config_audit_entries_retention_insert AFTER INSERT ON config_audit_entries BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes+(96+length(CAST(COALESCE(new.kind,'') AS BLOB))+length(CAST(COALESCE(new.actor_kind,'') AS BLOB))+length(CAST(COALESCE(new.actor,'') AS BLOB))+length(CAST(COALESCE(new.observer,'') AS BLOB))+length(CAST(COALESCE(new.service_id,'') AS BLOB))+length(CAST(COALESCE(new.operation_id,'') AS BLOB))+length(CAST(COALESCE(new.state,'') AS BLOB))+length(CAST(COALESCE(new.code,'') AS BLOB))+length(CAST(COALESCE(new.summary_json,'') AS BLOB))+length(CAST(COALESCE(new.changes_json,'') AS BLOB))+length(CAST(COALESCE(new.origin_kind,'') AS BLOB))+length(CAST(COALESCE(new.origin_id,'') AS BLOB))),audit_rows=audit_rows+1 WHERE singleton=1; END;
CREATE TRIGGER config_audit_entries_retention_delete AFTER DELETE ON config_audit_entries BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes-(96+length(CAST(COALESCE(old.kind,'') AS BLOB))+length(CAST(COALESCE(old.actor_kind,'') AS BLOB))+length(CAST(COALESCE(old.actor,'') AS BLOB))+length(CAST(COALESCE(old.observer,'') AS BLOB))+length(CAST(COALESCE(old.service_id,'') AS BLOB))+length(CAST(COALESCE(old.operation_id,'') AS BLOB))+length(CAST(COALESCE(old.state,'') AS BLOB))+length(CAST(COALESCE(old.code,'') AS BLOB))+length(CAST(COALESCE(old.summary_json,'') AS BLOB))+length(CAST(COALESCE(old.changes_json,'') AS BLOB))+length(CAST(COALESCE(old.origin_kind,'') AS BLOB))+length(CAST(COALESCE(old.origin_id,'') AS BLOB))),audit_rows=audit_rows-1 WHERE singleton=1; END;
CREATE TRIGGER config_audit_entries_retention_update AFTER UPDATE ON config_audit_entries BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes-(96+length(CAST(COALESCE(old.kind,'') AS BLOB))+length(CAST(COALESCE(old.actor_kind,'') AS BLOB))+length(CAST(COALESCE(old.actor,'') AS BLOB))+length(CAST(COALESCE(old.observer,'') AS BLOB))+length(CAST(COALESCE(old.service_id,'') AS BLOB))+length(CAST(COALESCE(old.operation_id,'') AS BLOB))+length(CAST(COALESCE(old.state,'') AS BLOB))+length(CAST(COALESCE(old.code,'') AS BLOB))+length(CAST(COALESCE(old.summary_json,'') AS BLOB))+length(CAST(COALESCE(old.changes_json,'') AS BLOB))+length(CAST(COALESCE(old.origin_kind,'') AS BLOB))+length(CAST(COALESCE(old.origin_id,'') AS BLOB)))+(96+length(CAST(COALESCE(new.kind,'') AS BLOB))+length(CAST(COALESCE(new.actor_kind,'') AS BLOB))+length(CAST(COALESCE(new.actor,'') AS BLOB))+length(CAST(COALESCE(new.observer,'') AS BLOB))+length(CAST(COALESCE(new.service_id,'') AS BLOB))+length(CAST(COALESCE(new.operation_id,'') AS BLOB))+length(CAST(COALESCE(new.state,'') AS BLOB))+length(CAST(COALESCE(new.code,'') AS BLOB))+length(CAST(COALESCE(new.summary_json,'') AS BLOB))+length(CAST(COALESCE(new.changes_json,'') AS BLOB))+length(CAST(COALESCE(new.origin_kind,'') AS BLOB))+length(CAST(COALESCE(new.origin_id,'') AS BLOB))) WHERE singleton=1; END;
CREATE TRIGGER config_audit_objects_retention_insert AFTER INSERT ON config_audit_objects BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes+(24+length(CAST(COALESCE(new.kind,'') AS BLOB))+length(CAST(COALESCE(new.name,'') AS BLOB))+length(CAST(COALESCE(new.action,'') AS BLOB))) WHERE singleton=1; END;
CREATE TRIGGER config_audit_objects_retention_delete AFTER DELETE ON config_audit_objects BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes-(24+length(CAST(COALESCE(old.kind,'') AS BLOB))+length(CAST(COALESCE(old.name,'') AS BLOB))+length(CAST(COALESCE(old.action,'') AS BLOB))) WHERE singleton=1; END;
CREATE TRIGGER config_audit_objects_retention_update AFTER UPDATE ON config_audit_objects BEGIN UPDATE config_audit_retention SET audit_bytes=audit_bytes-(24+length(CAST(COALESCE(old.kind,'') AS BLOB))+length(CAST(COALESCE(old.name,'') AS BLOB))+length(CAST(COALESCE(old.action,'') AS BLOB)))+(24+length(CAST(COALESCE(new.kind,'') AS BLOB))+length(CAST(COALESCE(new.name,'') AS BLOB))+length(CAST(COALESCE(new.action,'') AS BLOB))) WHERE singleton=1; END;
CREATE TRIGGER config_operation_events_retention_insert AFTER INSERT ON config_operation_events BEGIN UPDATE config_audit_retention SET event_bytes=event_bytes+(64+length(CAST(COALESCE(new.operation_id,'') AS BLOB))+length(CAST(COALESCE(new.state,'') AS BLOB))+length(CAST(COALESCE(new.code,'') AS BLOB))+length(CAST(COALESCE(new.changes_json,'') AS BLOB))+length(CAST(COALESCE(new.actor,'') AS BLOB))),event_rows=event_rows+1 WHERE singleton=1; END;
CREATE TRIGGER config_operation_events_retention_delete AFTER DELETE ON config_operation_events BEGIN UPDATE config_audit_retention SET event_bytes=event_bytes-(64+length(CAST(COALESCE(old.operation_id,'') AS BLOB))+length(CAST(COALESCE(old.state,'') AS BLOB))+length(CAST(COALESCE(old.code,'') AS BLOB))+length(CAST(COALESCE(old.changes_json,'') AS BLOB))+length(CAST(COALESCE(old.actor,'') AS BLOB))),event_rows=event_rows-1 WHERE singleton=1; END;
CREATE TRIGGER config_operation_events_retention_update AFTER UPDATE ON config_operation_events BEGIN UPDATE config_audit_retention SET event_bytes=event_bytes-(64+length(CAST(COALESCE(old.operation_id,'') AS BLOB))+length(CAST(COALESCE(old.state,'') AS BLOB))+length(CAST(COALESCE(old.code,'') AS BLOB))+length(CAST(COALESCE(old.changes_json,'') AS BLOB))+length(CAST(COALESCE(old.actor,'') AS BLOB)))+(64+length(CAST(COALESCE(new.operation_id,'') AS BLOB))+length(CAST(COALESCE(new.state,'') AS BLOB))+length(CAST(COALESCE(new.code,'') AS BLOB))+length(CAST(COALESCE(new.changes_json,'') AS BLOB))+length(CAST(COALESCE(new.actor,'') AS BLOB))) WHERE singleton=1; END;
